// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) (MemberRoleAssignment, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	DeleteRole(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetEveryoneRoleByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) (Role, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	ListRolesByWorkspace(ctx context.Context, arg ListRolesByWorkspaceParams) ([]Role, error)
	RemoveRoleFromMember(ctx context.Context, arg RemoveRoleFromMemberParams) (MemberRoleAssignment, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
}

var _ Querier = (*Queries)(nil)
