// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package infrastructure

import (
	"context"

	"github.com/google/uuid"
)

const assignRoleToMember = `-- name: AssignRoleToMember :one
INSERT INTO member_role_assignments (member_id, role_id) VALUES ($1, $2) RETURNING member_id, role_id
`

type AssignRoleToMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	RoleID   uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) (MemberRoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignRoleToMember, arg.MemberID, arg.RoleID)
	var i MemberRoleAssignment
	err := row.Scan(&i.MemberID, &i.RoleID)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    workspace_id,
    name,
    permission_bitmask,
    position,
    is_everyone
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, workspace_id, name, permission_bitmask, position, is_everyone, created_at, updated_at
`

type CreateRoleParams struct {
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	Name              string    `json:"name"`
	PermissionBitmask int64     `json:"permission_bitmask"`
	Position          int32     `json:"position"`
	IsEveryone        bool      `json:"is_everyone"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.WorkspaceID,
		arg.Name,
		arg.PermissionBitmask,
		arg.Position,
		arg.IsEveryone,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.PermissionBitmask,
		&i.Position,
		&i.IsEveryone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :one
DELETE FROM roles WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteRole, id)
	err := row.Scan(&id)
	return id, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, workspace_id, name, permission_bitmask, position, is_everyone, created_at, updated_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.PermissionBitmask,
		&i.Position,
		&i.IsEveryone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesByWorkspace = `-- name: ListRolesByWorkspace :many
SELECT id, workspace_id, name, permission_bitmask, position, is_everyone, created_at, updated_at
FROM roles
WHERE workspace_id = $1
ORDER BY position DESC
LIMIT $2 OFFSET $3
`

type ListRolesByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListRolesByWorkspace(ctx context.Context, arg ListRolesByWorkspaceParams) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.PermissionBitmask,
			&i.Position,
			&i.IsEveryone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromMember = `-- name: RemoveRoleFromMember :one
DELETE FROM member_role_assignments WHERE member_id = $1 AND role_id = $2 RETURNING member_id, role_id
`

type RemoveRoleFromMemberParams struct {
	MemberID uuid.UUID `json:"member_id"`
	RoleID   uuid.UUID `json:"role_id"`
}

func (q *Queries) RemoveRoleFromMember(ctx context.Context, arg RemoveRoleFromMemberParams) (MemberRoleAssignment, error) {
	row := q.db.QueryRowContext(ctx, removeRoleFromMember, arg.MemberID, arg.RoleID)
	var i MemberRoleAssignment
	err := row.Scan(&i.MemberID, &i.RoleID)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = $1, permission_bitmask = $2, position = $3, is_everyone = $4 WHERE id = $5 RETURNING id, workspace_id, name, permission_bitmask, position, is_everyone, created_at, updated_at
`

type UpdateRoleParams struct {
	Name              string    `json:"name"`
	PermissionBitmask int64     `json:"permission_bitmask"`
	Position          int32     `json:"position"`
	IsEveryone        bool      `json:"is_everyone"`
	ID                uuid.UUID `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, updateRole,
		arg.Name,
		arg.PermissionBitmask,
		arg.Position,
		arg.IsEveryone,
		arg.ID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.PermissionBitmask,
		&i.Position,
		&i.IsEveryone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
