// Package txcontext provides a typed context key for propagating database
// transactions across domain boundaries within a single request.
// Repositories call ExtractDBTX to transparently participate in an active
// transaction or fall back to the regular *sql.DB connection pool.
package txcontext

import (
	"context"
	"database/sql"
)

// DBTX is the common interface implemented by both *sql.DB and *sql.Tx,
// mirroring the interface generated by sqlc.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

type contextKey struct{}

// WithTx stores a *sql.Tx into the context.
func WithTx(ctx context.Context, tx *sql.Tx) context.Context {
	return context.WithValue(ctx, contextKey{}, tx)
}

// ExtractTx retrieves the *sql.Tx from the context, if present.
func ExtractTx(ctx context.Context) (*sql.Tx, bool) {
	tx, ok := ctx.Value(contextKey{}).(*sql.Tx)
	return tx, ok
}

// ExtractDBTX returns the *sql.Tx stored in ctx if a transaction is active,
// otherwise falls back to the provided *sql.DB. This allows repositories
// to transparently participate in transactions without explicit tx wiring.
func ExtractDBTX(ctx context.Context, fallback *sql.DB) DBTX {
	if tx, ok := ExtractTx(ctx); ok {
		return tx
	}
	return fallback
}
