version: "2"

linters:
  default: none
  enable:
    - depguard
    - gosec
    - errcheck
    - govet
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
          allow:
            - $gostd
            - github.com/iqbaljlldn/nexus
            - go.uber.org/zap
            - github.com/gin-gonic/gin
            - github.com/google/wire
            - github.com/swaggo/gin-swagger
            - github.com/swaggo/files
            - github.com/google/uuid
            - gopkg.in/natefinch/lumberjack.v2
            - go.opentelemetry.io
            - github.com/prometheus
            - github.com/redis/go-redis/v9
            - github.com/jackc/pgx/v5
            - github.com/sqlc-dev/pqtype
            - golang.org/x/crypto/argon2
            - github.com/stretchr/testify
            - github.com/golang-jwt/jwt/v5
            - github.com/swaggo/swag
            - github.com/alicebob/miniredis/v2

formatters:
  enable:
    - gofmt

run:
  timeout: 5m
