// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByEmailOrUsername(ctx context.Context, arg FindUserByEmailOrUsernameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
