// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package infrastructure

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, user_id, refresh_token_hash, user_agent, ip_address, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, status, expires_at, created_at
`

type CreateSessionParams struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	UserAgent        sql.NullString `json:"user_agent"`
	IpAddress        pqtype.Inet    `json:"ip_address"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, username, display_name, password_hash, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, email, username, display_name, password_hash, avatar_url, is_suspended, is_banned, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsSuspended,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findActiveSessionsByUserId = `-- name: FindActiveSessionsByUserId :many
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, status, expires_at, created_at
FROM sessions
WHERE
    user_id = $1
    AND deleted_at IS NULL
    AND status = 'active'
`

func (q *Queries) FindActiveSessionsByUserId(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, findActiveSessionsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionById = `-- name: FindSessionById :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, status, expires_at, created_at
FROM sessions
WHERE
    id = $1
    AND deleted_at IS NULL
    AND status = 'active'
LIMIT 1
`

func (q *Queries) FindSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, status, expires_at, created_at FROM sessions
WHERE
    refresh_token_hash = $1
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) FindSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, username, display_name, password_hash, avatar_url, is_suspended, is_banned, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsSuspended,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, email, username, display_name, password_hash, avatar_url, is_suspended, is_banned, created_at, updated_at, deleted_at FROM users
WHERE username = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsSuspended,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeAllSessionsByUserId = `-- name: RevokeAllSessionsByUserId :exec
UPDATE sessions
SET 
    deleted_at = now(),
    updated_at = now(),
    status = 'revoked'
WHERE
    user_id = $1
    AND deleted_at IS NULL
    AND status = 'active'
`

func (q *Queries) RevokeAllSessionsByUserId(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeAllSessionsByUserId, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions
SET 
    deleted_at = now(),
    updated_at = now(),
    status = 'revoked'
WHERE
    refresh_token_hash = $1
    AND deleted_at IS NULL
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, status, expires_at, created_at
`

func (q *Queries) RevokeSession(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, revokeSession, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSessionById = `-- name: RevokeSessionById :one
UPDATE sessions
SET
    deleted_at = now(),
    updated_at = now(),
    status = 'revoked'
WHERE
    id = $1
    AND deleted_at IS NULL
    AND status = 'active'
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, status, expires_at, created_at
`

func (q *Queries) RevokeSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, revokeSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
