// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
