// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package infrastructure

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, refresh_token_hash, user_agent, ip_address, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, status, expires_at, created_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	UserAgent        sql.NullString `json:"user_agent"`
	IpAddress        pqtype.Inet    `json:"ip_address"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, username, display_name, password_hash
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, username, display_name, password_hash, avatar_url, is_suspended, is_banned, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsSuspended,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByEmailOrUsername = `-- name: FindUserByEmailOrUsername :one
SELECT id, email, username, display_name, password_hash, avatar_url, is_suspended, is_banned, created_at, updated_at, deleted_at FROM users
WHERE (email = $1 OR username = $2) AND deleted_at IS NULL
LIMIT 1
`

type FindUserByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) FindUserByEmailOrUsername(ctx context.Context, arg FindUserByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.IsSuspended,
		&i.IsBanned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
