services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    env_file: ./.env
    shm_size: 128mb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - postgres_logs:/var/log/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command:
      - postgres

      # Memory
      - -c
      - shared_buffers=128MB
      - -c
      - effective_cache_size=1GB
      - -c
      - work_mem=8MB
      - -c
      - maintenance_work_mem=256MB

      # WAL
      - -c
      - wal_buffers=16MB
      - -c
      - min_wal_size=512MB
      - -c
      - max_wal_size=2GB
      - -c
      - wal_compression=on

      # Checkpoint
      - -c
      - checkpoint_completion_target=0.9

      # Parallelism
      - -c
      - max_worker_processes=8
      - -c
      - max_parallel_workers=8
      - -c
      - max_parallel_workers_per_gather=4

      # Connection
      - -c
      - max_connections=200

      # Planner
      - -c
      - random_page_cost=1.1
      - -c
      - effective_io_concurrency=200

      # Logging
      - -c
      - logging_collector=off
      - -c
      - log_directory=/var/log/postgresql
      - -c
      - log_filename=postgresql-%Y-%m-%d.log
      - -c
      - log_rotation_age=1d
      - -c
      - log_rotation_size=100MB
      - -c
      - log_connections=on
      - -c
      - log_disconnections=on
      - -c
      - log_checkpoints=on
      - -c
      - log_lock_waits=on
      - -c
      - log_temp_files=0
      - -c
      - log_min_duration_statement=500

      # Statistics
      - -c
      - shared_preload_libraries=pg_stat_statements

      - -c
      - pg_stat_statements.max=10000
      - -c
      - pg_stat_statements.track=all

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest

    restart: unless-stopped

    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "9187:9187"

  prometheus:
    image: prom/prometheus:latest

    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_data:/var/lib/grafana

  postgres_backup:
    image: postgres:18

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./backup:/backup

    entrypoint: >
      sh -c "
      while true;
      do
        pg_dump
        -h postgres
        -U ${POSTGRES_USER}
        -Fc
        ${POSTGRES_DB}
        > /backup/backup-$$(date +%F-%H-%M).dump;

        find /backup -type f -mtime +7 -delete;

        sleep 86400;
      done
      "

  adminer:
    image: adminer
    restart: always
    ports: 
      - 1000:1000

  # traefik:
  #   image: traefik:v3.1
  #   command:
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minioadmin}"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER:-minioadmin} $${MINIO_ROOT_PASSWORD:-minioadmin};
      /usr/bin/mc mb --ignore-existing myminio/nexus-attachments;
      /usr/bin/mc mb --ignore-existing myminio/nexus-avatars;
      /usr/bin/mc anonymous set public myminio/nexus-attachments;
      /usr/bin/mc anonymous set public myminio/nexus-avatars;
      exit 0;
      "

  api:
    image: ghcr.io/iqbaljlldn/nexus/api:latest
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started

  web:
    image: ghcr.io/iqbaljlldn/nexus/web:latest
    build:
      context: ../../apps/web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=3001"
    depends_on:
      - api

volumes:
  postgres_data:
  postgres_logs:
  grafana_data:
  redis_data:
  minio_data: