// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateChannelPermissionOverride(ctx context.Context, arg CreateChannelPermissionOverrideParams) (ChannelPermissionOverride, error)
	DeleteChannelPermissionOverride(ctx context.Context, id uuid.UUID) error
	GetCategoryWorkspaceID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error)
	GetChannelPermissionOverrideByMember(ctx context.Context, arg GetChannelPermissionOverrideByMemberParams) (ChannelPermissionOverride, error)
	GetChannelPermissionOverrideByRole(ctx context.Context, arg GetChannelPermissionOverrideByRoleParams) (ChannelPermissionOverride, error)
	GetChannelPermissionOverrides(ctx context.Context, channelID uuid.UUID) ([]ChannelPermissionOverride, error)
	GetMaxChannelPosition(ctx context.Context, workspaceID uuid.NullUUID) (int32, error)
	ListChannelsByWorkspaceID(ctx context.Context, workspaceID uuid.NullUUID) ([]Channel, error)
	SoftDeleteChannel(ctx context.Context, id uuid.UUID) error
	UpdateChannelName(ctx context.Context, arg UpdateChannelNameParams) (Channel, error)
	UpdateChannelPermissionOverride(ctx context.Context, arg UpdateChannelPermissionOverrideParams) (ChannelPermissionOverride, error)
	UpdateChannelPosition(ctx context.Context, arg UpdateChannelPositionParams) (Channel, error)
}

var _ Querier = (*Queries)(nil)
