// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package infrastructure

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
    workspace_id, category_id, type, name, position
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, workspace_id, category_id, type, name, participant_key, position, created_at, deleted_at
`

type CreateChannelParams struct {
	WorkspaceID uuid.NullUUID  `json:"workspace_id"`
	CategoryID  uuid.NullUUID  `json:"category_id"`
	Type        string         `json:"type"`
	Name        sql.NullString `json:"name"`
	Position    int32          `json:"position"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.WorkspaceID,
		arg.CategoryID,
		arg.Type,
		arg.Name,
		arg.Position,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.ParticipantKey,
		&i.Position,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createChannelPermissionOverride = `-- name: CreateChannelPermissionOverride :one
INSERT INTO channel_permission_overrides (
    channel_id, role_id, member_id, allow_bitmask, deny_bitmask
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, channel_id, role_id, member_id, allow_bitmask, deny_bitmask
`

type CreateChannelPermissionOverrideParams struct {
	ChannelID    uuid.UUID     `json:"channel_id"`
	RoleID       uuid.NullUUID `json:"role_id"`
	MemberID     uuid.NullUUID `json:"member_id"`
	AllowBitmask int64         `json:"allow_bitmask"`
	DenyBitmask  int64         `json:"deny_bitmask"`
}

func (q *Queries) CreateChannelPermissionOverride(ctx context.Context, arg CreateChannelPermissionOverrideParams) (ChannelPermissionOverride, error) {
	row := q.db.QueryRowContext(ctx, createChannelPermissionOverride,
		arg.ChannelID,
		arg.RoleID,
		arg.MemberID,
		arg.AllowBitmask,
		arg.DenyBitmask,
	)
	var i ChannelPermissionOverride
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.RoleID,
		&i.MemberID,
		&i.AllowBitmask,
		&i.DenyBitmask,
	)
	return i, err
}

const deleteChannelPermissionOverride = `-- name: DeleteChannelPermissionOverride :exec
DELETE FROM channel_permission_overrides
WHERE id = $1
`

func (q *Queries) DeleteChannelPermissionOverride(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChannelPermissionOverride, id)
	return err
}

const getCategoryWorkspaceID = `-- name: GetCategoryWorkspaceID :one
SELECT workspace_id FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryWorkspaceID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getCategoryWorkspaceID, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, workspace_id, category_id, type, name, participant_key, position, created_at, deleted_at FROM channels
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.ParticipantKey,
		&i.Position,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelPermissionOverrideByMember = `-- name: GetChannelPermissionOverrideByMember :one
SELECT id, channel_id, role_id, member_id, allow_bitmask, deny_bitmask FROM channel_permission_overrides
WHERE channel_id = $1 AND member_id = $2
`

type GetChannelPermissionOverrideByMemberParams struct {
	ChannelID uuid.UUID     `json:"channel_id"`
	MemberID  uuid.NullUUID `json:"member_id"`
}

func (q *Queries) GetChannelPermissionOverrideByMember(ctx context.Context, arg GetChannelPermissionOverrideByMemberParams) (ChannelPermissionOverride, error) {
	row := q.db.QueryRowContext(ctx, getChannelPermissionOverrideByMember, arg.ChannelID, arg.MemberID)
	var i ChannelPermissionOverride
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.RoleID,
		&i.MemberID,
		&i.AllowBitmask,
		&i.DenyBitmask,
	)
	return i, err
}

const getChannelPermissionOverrideByRole = `-- name: GetChannelPermissionOverrideByRole :one
SELECT id, channel_id, role_id, member_id, allow_bitmask, deny_bitmask FROM channel_permission_overrides
WHERE channel_id = $1 AND role_id = $2
`

type GetChannelPermissionOverrideByRoleParams struct {
	ChannelID uuid.UUID     `json:"channel_id"`
	RoleID    uuid.NullUUID `json:"role_id"`
}

func (q *Queries) GetChannelPermissionOverrideByRole(ctx context.Context, arg GetChannelPermissionOverrideByRoleParams) (ChannelPermissionOverride, error) {
	row := q.db.QueryRowContext(ctx, getChannelPermissionOverrideByRole, arg.ChannelID, arg.RoleID)
	var i ChannelPermissionOverride
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.RoleID,
		&i.MemberID,
		&i.AllowBitmask,
		&i.DenyBitmask,
	)
	return i, err
}

const getChannelPermissionOverrides = `-- name: GetChannelPermissionOverrides :many
SELECT id, channel_id, role_id, member_id, allow_bitmask, deny_bitmask FROM channel_permission_overrides
WHERE channel_id = $1
`

func (q *Queries) GetChannelPermissionOverrides(ctx context.Context, channelID uuid.UUID) ([]ChannelPermissionOverride, error) {
	rows, err := q.db.QueryContext(ctx, getChannelPermissionOverrides, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelPermissionOverride
	for rows.Next() {
		var i ChannelPermissionOverride
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.RoleID,
			&i.MemberID,
			&i.AllowBitmask,
			&i.DenyBitmask,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxChannelPosition = `-- name: GetMaxChannelPosition :one
SELECT COALESCE(MAX(position), 0)::int
FROM channels
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMaxChannelPosition(ctx context.Context, workspaceID uuid.NullUUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxChannelPosition, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listChannelsByWorkspaceID = `-- name: ListChannelsByWorkspaceID :many
SELECT id, workspace_id, category_id, type, name, participant_key, position, created_at, deleted_at FROM channels
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListChannelsByWorkspaceID(ctx context.Context, workspaceID uuid.NullUUID) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CategoryID,
			&i.Type,
			&i.Name,
			&i.ParticipantKey,
			&i.Position,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChannel = `-- name: SoftDeleteChannel :exec
UPDATE channels
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteChannel, id)
	return err
}

const updateChannelName = `-- name: UpdateChannelName :one
UPDATE channels
SET name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, category_id, type, name, participant_key, position, created_at, deleted_at
`

type UpdateChannelNameParams struct {
	ID   uuid.UUID      `json:"id"`
	Name sql.NullString `json:"name"`
}

func (q *Queries) UpdateChannelName(ctx context.Context, arg UpdateChannelNameParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannelName, arg.ID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.ParticipantKey,
		&i.Position,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateChannelPermissionOverride = `-- name: UpdateChannelPermissionOverride :one
UPDATE channel_permission_overrides
SET allow_bitmask = $2, deny_bitmask = $3
WHERE id = $1
RETURNING id, channel_id, role_id, member_id, allow_bitmask, deny_bitmask
`

type UpdateChannelPermissionOverrideParams struct {
	ID           uuid.UUID `json:"id"`
	AllowBitmask int64     `json:"allow_bitmask"`
	DenyBitmask  int64     `json:"deny_bitmask"`
}

func (q *Queries) UpdateChannelPermissionOverride(ctx context.Context, arg UpdateChannelPermissionOverrideParams) (ChannelPermissionOverride, error) {
	row := q.db.QueryRowContext(ctx, updateChannelPermissionOverride, arg.ID, arg.AllowBitmask, arg.DenyBitmask)
	var i ChannelPermissionOverride
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.RoleID,
		&i.MemberID,
		&i.AllowBitmask,
		&i.DenyBitmask,
	)
	return i, err
}

const updateChannelPosition = `-- name: UpdateChannelPosition :one
UPDATE channels
SET position = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, category_id, type, name, participant_key, position, created_at, deleted_at
`

type UpdateChannelPositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) UpdateChannelPosition(ctx context.Context, arg UpdateChannelPositionParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannelPosition, arg.ID, arg.Position)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CategoryID,
		&i.Type,
		&i.Name,
		&i.ParticipantKey,
		&i.Position,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
