// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Category struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Position    int32     `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
}

type Channel struct {
	ID             uuid.UUID      `json:"id"`
	WorkspaceID    uuid.NullUUID  `json:"workspace_id"`
	CategoryID     uuid.NullUUID  `json:"category_id"`
	Type           string         `json:"type"`
	Name           sql.NullString `json:"name"`
	ParticipantKey sql.NullString `json:"participant_key"`
	Position       int32          `json:"position"`
	CreatedAt      time.Time      `json:"created_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

type ChannelPermissionOverride struct {
	ID           uuid.UUID     `json:"id"`
	ChannelID    uuid.UUID     `json:"channel_id"`
	RoleID       uuid.NullUUID `json:"role_id"`
	MemberID     uuid.NullUUID `json:"member_id"`
	AllowBitmask int64         `json:"allow_bitmask"`
	DenyBitmask  int64         `json:"deny_bitmask"`
}

type Invite struct {
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Code        string        `json:"code"`
	CreatedBy   uuid.UUID     `json:"created_by"`
	MaxUses     sql.NullInt32 `json:"max_uses"`
	UseCount    int32         `json:"use_count"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
	CreatedAt   time.Time     `json:"created_at"`
}

type Member struct {
	ID          uuid.UUID      `json:"id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Nickname    sql.NullString `json:"nickname"`
	JoinedAt    time.Time      `json:"joined_at"`
}

type MemberRoleAssignment struct {
	MemberID uuid.UUID `json:"member_id"`
	RoleID   uuid.UUID `json:"role_id"`
}

type Role struct {
	ID                uuid.UUID `json:"id"`
	WorkspaceID       uuid.UUID `json:"workspace_id"`
	Name              string    `json:"name"`
	PermissionBitmask int64     `json:"permission_bitmask"`
	Position          int32     `json:"position"`
	IsEveryone        bool      `json:"is_everyone"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	UserAgent        sql.NullString `json:"user_agent"`
	IpAddress        pqtype.Inet    `json:"ip_address"`
	Status           string         `json:"status"`
	ExpiresAt        time.Time      `json:"expires_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	Username     string         `json:"username"`
	DisplayName  string         `json:"display_name"`
	PasswordHash string         `json:"password_hash"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	IsSuspended  bool           `json:"is_suspended"`
	IsBanned     bool           `json:"is_banned"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type Workspace struct {
	ID        uuid.UUID      `json:"id"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	Name      string         `json:"name"`
	IconUrl   sql.NullString `json:"icon_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
