// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	FindInviteByCode(ctx context.Context, code string) (Invite, error)
	IncrementInviteUseCount(ctx context.Context, id uuid.UUID) (Invite, error)
	ListWorkspacesByUserID(ctx context.Context, arg ListWorkspacesByUserIDParams) ([]Workspace, error)
}

var _ Querier = (*Queries)(nil)
