// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package infrastructure

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (workspace_id, name)
VALUES ($1, $2)
RETURNING id, workspace_id, name, position, created_at
`

type CreateCategoryParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.WorkspaceID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (workspace_id, code, created_by, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, code, created_by, max_uses, use_count, expires_at, created_at
`

type CreateInviteParams struct {
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Code        string        `json:"code"`
	CreatedBy   uuid.UUID     `json:"created_by"`
	MaxUses     sql.NullInt32 `json:"max_uses"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.WorkspaceID,
		arg.Code,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (owner_id, name, icon_url)
VALUES ($1, $2, $3)
RETURNING id, owner_id, name, icon_url, created_at, updated_at, deleted_at
`

type CreateWorkspaceParams struct {
	OwnerID uuid.UUID      `json:"owner_id"`
	Name    string         `json:"name"`
	IconUrl sql.NullString `json:"icon_url"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.OwnerID, arg.Name, arg.IconUrl)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findInviteByCode = `-- name: FindInviteByCode :one
SELECT id, workspace_id, code, created_by, max_uses, use_count, expires_at, created_at FROM invites
WHERE code = $1
`

func (q *Queries) FindInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRowContext(ctx, findInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspacesCountByUserID = `-- name: GetWorkspacesCountByUserID :one
SELECT count(*) 
FROM workspaces w
JOIN members m ON w.id = m.workspace_id
WHERE m.user_id = $1
  AND ($2::text IS NULL OR w.name ILIKE '%' || $2::text || '%')
`

type GetWorkspacesCountByUserIDParams struct {
	UserID uuid.UUID      `json:"user_id"`
	Search sql.NullString `json:"search"`
}

func (q *Queries) GetWorkspacesCountByUserID(ctx context.Context, arg GetWorkspacesCountByUserIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWorkspacesCountByUserID, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementInviteUseCount = `-- name: IncrementInviteUseCount :one
UPDATE invites
SET use_count = use_count + 1
WHERE id = $1 AND (max_uses IS NULL OR use_count < max_uses)
RETURNING id, workspace_id, code, created_by, max_uses, use_count, expires_at, created_at
`

func (q *Queries) IncrementInviteUseCount(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRowContext(ctx, incrementInviteUseCount, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspacesByNameAsc = `-- name: ListWorkspacesByNameAsc :many
SELECT w.id, w.owner_id, w.name, w.icon_url, w.created_at, w.updated_at, w.deleted_at 
FROM workspaces w
JOIN members m ON w.id = m.workspace_id
WHERE m.user_id = $1 
  AND ($3::text IS NULL OR w.name ILIKE '%' || $3::text || '%')
  AND (
    $4::text IS NULL OR 
    (w.name, w.id) > ($4::text, $5::uuid)
  )
ORDER BY w.name ASC, w.id ASC
LIMIT $2
`

type ListWorkspacesByNameAscParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Limit      int32          `json:"limit"`
	Search     sql.NullString `json:"search"`
	CursorName sql.NullString `json:"cursor_name"`
	CursorID   uuid.NullUUID  `json:"cursor_id"`
}

func (q *Queries) ListWorkspacesByNameAsc(ctx context.Context, arg ListWorkspacesByNameAscParams) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByNameAsc,
		arg.UserID,
		arg.Limit,
		arg.Search,
		arg.CursorName,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IconUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByNewest = `-- name: ListWorkspacesByNewest :many
SELECT w.id, w.owner_id, w.name, w.icon_url, w.created_at, w.updated_at, w.deleted_at 
FROM workspaces w
JOIN members m ON w.id = m.workspace_id
WHERE m.user_id = $1 
  AND ($3::text IS NULL OR w.name ILIKE '%' || $3::text || '%')
  AND (
    $4::timestamptz IS NULL OR 
    (w.created_at, w.id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY w.created_at DESC, w.id DESC
LIMIT $2
`

type ListWorkspacesByNewestParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	Limit           int32          `json:"limit"`
	Search          sql.NullString `json:"search"`
	CursorCreatedAt sql.NullTime   `json:"cursor_created_at"`
	CursorID        uuid.NullUUID  `json:"cursor_id"`
}

func (q *Queries) ListWorkspacesByNewest(ctx context.Context, arg ListWorkspacesByNewestParams) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByNewest,
		arg.UserID,
		arg.Limit,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IconUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
