// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package infrastructure

import (
	"context"
)

type Querier interface {
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	FindMemberByWorkspaceAndUser(ctx context.Context, arg FindMemberByWorkspaceAndUserParams) (Member, error)
	ListMembersByWorkspace(ctx context.Context, arg ListMembersByWorkspaceParams) ([]Member, error)
}

var _ Querier = (*Queries)(nil)
