// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package infrastructure

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (workspace_id, user_id, nickname)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, user_id, nickname, joined_at
`

type CreateMemberParams struct {
	WorkspaceID uuid.UUID      `json:"workspace_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Nickname    sql.NullString `json:"nickname"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, createMember, arg.WorkspaceID, arg.UserID, arg.Nickname)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
	)
	return i, err
}

const findMemberByWorkspaceAndUser = `-- name: FindMemberByWorkspaceAndUser :one
SELECT id, workspace_id, user_id, nickname, joined_at FROM members
WHERE workspace_id = $1 AND user_id = $2
`

type FindMemberByWorkspaceAndUserParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) FindMemberByWorkspaceAndUser(ctx context.Context, arg FindMemberByWorkspaceAndUserParams) (Member, error) {
	row := q.db.QueryRowContext(ctx, findMemberByWorkspaceAndUser, arg.WorkspaceID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
	)
	return i, err
}

const listMembersByWorkspace = `-- name: ListMembersByWorkspace :many
SELECT id, workspace_id, user_id, nickname, joined_at FROM members
WHERE workspace_id = $1 AND ($3::uuid IS NULL OR id > $3::uuid)
ORDER BY id ASC
LIMIT $2
`

type ListMembersByWorkspaceParams struct {
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Limit       int32         `json:"limit"`
	Cursor      uuid.NullUUID `json:"cursor"`
}

func (q *Queries) ListMembersByWorkspace(ctx context.Context, arg ListMembersByWorkspaceParams) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByWorkspace, arg.WorkspaceID, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Nickname,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
